# Hypermesh Nexus Core Configuration
# Gateway Coin Production Configuration

[node]
id = "gateway-coin-nexus-primary"
cluster_name = "gateway-coin-production"
log_level = "INFO"
bind_address = "0.0.0.0"
external_address = "0.0.0.0"

[api]
http_port = 8080
https_port = 8443
metrics_port = 9090
enable_cors = true
cors_origins = ["*"]

[consensus]
algorithm = "byzantine-fault-tolerant"
min_nodes = 3
max_nodes = 100
consensus_timeout = "5s"
heartbeat_interval = "1s"
election_timeout = "10s"

[transport]
# QUIC over IPv6 Configuration
protocol = "quic"
port = 4001
enable_ipv6 = true
enable_encryption = true
max_connections = 1000
connection_timeout = "30s"
keep_alive_interval = "10s"

# TLS Configuration for QUIC
[transport.tls]
cert_file = "/certs/nexus.crt"
key_file = "/certs/nexus.key"
ca_file = "/certs/ca.crt"
verify_client_cert = true
min_tls_version = "1.3"
cipher_suites = [
    "TLS_AES_256_GCM_SHA384",
    "TLS_CHACHA20_POLY1305_SHA256",
    "TLS_AES_128_GCM_SHA256"
]

[state]
backend = "distributed-redis"
replication_factor = 3
consistency_level = "strong"
snapshot_interval = "300s"
compaction_interval = "3600s"

[state.redis]
cluster_nodes = [
    "redis-cluster-1:7001",
    "redis-cluster-2:7002",
    "redis-cluster-3:7003"
]
pool_size = 10
timeout = "5s"
retry_attempts = 3

[storage]
data_dir = "/data"
max_log_size = "1GB"
retention_days = 30
compression = "zstd"

[metrics]
enabled = true
port = 9090
path = "/metrics"
interval = "10s"
retention = "168h"  # 7 days

[stoq_integration]
enabled = true
endpoint = "http://stoq-engine:8081"
api_key = "gateway-coin-stoq-integration-key"
metrics_collection = true
anomaly_detection = true
threat_scoring = true
economic_monitoring = true

[stoq_integration.ebpf]
enabled = true
programs = [
    "network_stats",
    "memory_stats",
    "cpu_stats",
    "transaction_stats",
    "consensus_stats"
]
collection_interval = "1s"
buffer_size = 1024

[security]
enable_audit_log = true
audit_log_path = "/data/audit.log"
max_request_size = "10MB"
rate_limit = 1000  # requests per minute
enable_firewall = true

[security.authentication]
method = "certificate"
cert_authority = "/certs/ca.crt"
require_client_cert = true
cert_validation = "strict"

[security.encryption]
algorithm = "AES-256-GCM"
key_rotation_interval = "24h"
forward_secrecy = true

[performance]
# Performance tuning for Gateway Coin requirements
max_transactions_per_second = 5000
max_concurrent_connections = 2000
worker_threads = 8
io_threads = 4
async_batch_size = 100

[performance.cache]
enabled = true
max_size = "512MB"
ttl = "300s"
cleanup_interval = "60s"

[development]
# Development environment specific settings
enable_debug_endpoints = false
hot_reload = false
profiling = false
trace_requests = false

[gateway_coin]
# Gateway Coin specific configuration
token_symbol = "GATE"
decimals = 18
initial_supply = "1000000000000000000000000000"  # 1B tokens
demurrage_enabled = true
demurrage_rate = "0.0001"  # 0.01% per day
anti_speculation_enabled = true
max_transaction_value = "10000000000000000000000"  # 10K GATE per transaction
circuit_breaker_threshold = "50000000000000000000000"  # 50K GATE per hour

[gateway_coin.chains]
# Supported chain configurations
ethereum = { enabled = true, rpc_url = "https://mainnet.infura.io/v3/269cd6aa735d4e7dbfa0deeef9fe3969", chain_id = 1 }
polygon = { enabled = true, rpc_url = "https://polygon-mainnet.infura.io/v3/269cd6aa735d4e7dbfa0deeef9fe3969", chain_id = 137 }
solana = { enabled = true, rpc_url = "https://api.mainnet-beta.solana.com", cluster = "mainnet-beta" }
near = { enabled = true, rpc_url = "https://rpc.mainnet.near.org", network_id = "mainnet" }
cosmos = { enabled = true, rpc_url = "https://rpc-cosmoshub.keplr.app", chain_id = "cosmoshub-4" }
radix = { enabled = true, gateway_url = "https://mainnet.radixdlt.com", network_id = "mainnet" }

[logging]
level = "INFO"
format = "json"
output = "stdout"
rotation = true
max_file_size = "100MB"
max_files = 10

[logging.audit]
enabled = true
file = "/data/audit.log"
include_request_body = false
include_response_body = false
retention_days = 90